/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `username` VARCHAR(255) NOT NULL PRIMARY KEY,
  `password` TEXT NOT NULL,
  `name` TEXT NOT NULL,
  `maildir` TEXT NOT NULL,
  `quota` BIGINT UNSIGNED NOT NULL,
  `local_part` TEXT NOT NULL,
  `domain` TEXT NOT NULL,
  `recovery_mail` TEXT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `active` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

