// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `UserManagementInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __UserManagementInterface_h__
#define __UserManagementInterface_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace UserManagementInterface
{

class RPCObject;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::UserManagementInterface::RPCObject>&);
::IceProxy::Ice::Object* upCast(::IceProxy::UserManagementInterface::RPCObject*);

}

}

namespace UserManagementInterface
{

class RPCObject;
bool operator==(const RPCObject&, const RPCObject&);
bool operator<(const RPCObject&, const RPCObject&);
::Ice::Object* upCast(::UserManagementInterface::RPCObject*);
typedef ::IceInternal::Handle< ::UserManagementInterface::RPCObject> RPCObjectPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::UserManagementInterface::RPCObject> RPCObjectPrx;
void __patch(RPCObjectPtr&, const ::Ice::ObjectPtr&);

}

namespace UserManagementInterface
{

enum statuscode
{
    SUCCESS,
    FAILURE,
    FAILUREUSEREXISTS,
    FAILUREEMPTYSTRING
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::UserManagementInterface::statuscode>
{
    static const StreamHelperCategory helper = StreamHelperCategoryEnum;
    static const int minValue = 0;
    static const int maxValue = 3;
    static const int minWireSize = 1;
    static const bool fixedLength = false;
};

}

namespace UserManagementInterface
{

class Callback_RPCObject_addUser_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RPCObject_addUser_Base> Callback_RPCObject_addUserPtr;

class Callback_RPCObject_changeUserPassword_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RPCObject_changeUserPassword_Base> Callback_RPCObject_changeUserPasswordPtr;

class Callback_RPCObject_changeUserQuota_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RPCObject_changeUserQuota_Base> Callback_RPCObject_changeUserQuotaPtr;

class Callback_RPCObject_existsUser_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RPCObject_existsUser_Base> Callback_RPCObject_existsUserPtr;

class Callback_RPCObject_userCount_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_RPCObject_userCount_Base> Callback_RPCObject_userCountPtr;

}

namespace IceProxy
{

namespace UserManagementInterface
{

class RPCObject : virtual public ::IceProxy::Ice::Object
{
public:

    ::UserManagementInterface::statuscode addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active)
    {
        return addUser(username, name, password, domain, quota, active, 0);
    }
    ::UserManagementInterface::statuscode addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context& __ctx)
    {
        return addUser(username, name, password, domain, quota, active, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_addUser(username, name, password, domain, quota, active, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addUser(username, name, password, domain, quota, active, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_addUser(username, name, password, domain, quota, active, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_addUser(username, name, password, domain, quota, active, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::UserManagementInterface::statuscode)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
                ::UserManagementInterface::statuscode __ret;
                try
                {
                    __ret = __proxy->end_addUser(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::UserManagementInterface::statuscode)> _response;
        };
        return begin_addUser(username, name, password, domain, quota, active, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active)
    {
        return begin_addUser(username, name, password, domain, quota, active, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context& __ctx)
    {
        return begin_addUser(username, name, password, domain, quota, active, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUser(username, name, password, domain, quota, active, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUser(username, name, password, domain, quota, active, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::UserManagementInterface::Callback_RPCObject_addUserPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUser(username, name, password, domain, quota, active, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context& __ctx, const ::UserManagementInterface::Callback_RPCObject_addUserPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_addUser(username, name, password, domain, quota, active, &__ctx, __del, __cookie);
    }

    ::UserManagementInterface::statuscode end_addUser(const ::Ice::AsyncResultPtr&);
    
private:

    ::UserManagementInterface::statuscode addUser(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, ::Ice::Long, bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_addUser(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, ::Ice::Long, bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::UserManagementInterface::statuscode changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword)
    {
        return changeUserPassword(usernam, newpassword, 0);
    }
    ::UserManagementInterface::statuscode changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context& __ctx)
    {
        return changeUserPassword(usernam, newpassword, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_changeUserPassword(usernam, newpassword, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_changeUserPassword(usernam, newpassword, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_changeUserPassword(usernam, newpassword, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_changeUserPassword(usernam, newpassword, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::UserManagementInterface::statuscode)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
                ::UserManagementInterface::statuscode __ret;
                try
                {
                    __ret = __proxy->end_changeUserPassword(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::UserManagementInterface::statuscode)> _response;
        };
        return begin_changeUserPassword(usernam, newpassword, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword)
    {
        return begin_changeUserPassword(usernam, newpassword, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context& __ctx)
    {
        return begin_changeUserPassword(usernam, newpassword, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserPassword(usernam, newpassword, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserPassword(usernam, newpassword, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::UserManagementInterface::Callback_RPCObject_changeUserPasswordPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserPassword(usernam, newpassword, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context& __ctx, const ::UserManagementInterface::Callback_RPCObject_changeUserPasswordPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserPassword(usernam, newpassword, &__ctx, __del, __cookie);
    }

    ::UserManagementInterface::statuscode end_changeUserPassword(const ::Ice::AsyncResultPtr&);
    
private:

    ::UserManagementInterface::statuscode changeUserPassword(const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_changeUserPassword(const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::UserManagementInterface::statuscode changeUserQuota(const ::std::string& username, ::Ice::Long quota)
    {
        return changeUserQuota(username, quota, 0);
    }
    ::UserManagementInterface::statuscode changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context& __ctx)
    {
        return changeUserQuota(username, quota, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_changeUserQuota(username, quota, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_changeUserQuota(username, quota, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_changeUserQuota(username, quota, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_changeUserQuota(username, quota, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::UserManagementInterface::statuscode)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::UserManagementInterface::statuscode)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
                ::UserManagementInterface::statuscode __ret;
                try
                {
                    __ret = __proxy->end_changeUserQuota(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::UserManagementInterface::statuscode)> _response;
        };
        return begin_changeUserQuota(username, quota, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota)
    {
        return begin_changeUserQuota(username, quota, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context& __ctx)
    {
        return begin_changeUserQuota(username, quota, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserQuota(username, quota, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserQuota(username, quota, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::UserManagementInterface::Callback_RPCObject_changeUserQuotaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserQuota(username, quota, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context& __ctx, const ::UserManagementInterface::Callback_RPCObject_changeUserQuotaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_changeUserQuota(username, quota, &__ctx, __del, __cookie);
    }

    ::UserManagementInterface::statuscode end_changeUserQuota(const ::Ice::AsyncResultPtr&);
    
private:

    ::UserManagementInterface::statuscode changeUserQuota(const ::std::string&, ::Ice::Long, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_changeUserQuota(const ::std::string&, ::Ice::Long, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool existsUser(const ::std::string& username)
    {
        return existsUser(username, 0);
    }
    bool existsUser(const ::std::string& username, const ::Ice::Context& __ctx)
    {
        return existsUser(username, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_existsUser(const ::std::string& username, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_existsUser(username, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_existsUser(const ::std::string& username, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_existsUser(username, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_existsUser(const ::std::string& username, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_existsUser(username, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_existsUser(const ::std::string& username, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_existsUser(username, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_existsUser(const ::std::string& username, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_existsUser(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_existsUser(username, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string& username)
    {
        return begin_existsUser(username, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string& username, const ::Ice::Context& __ctx)
    {
        return begin_existsUser(username, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string& username, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_existsUser(username, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string& username, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_existsUser(username, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string& username, const ::UserManagementInterface::Callback_RPCObject_existsUserPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_existsUser(username, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string& username, const ::Ice::Context& __ctx, const ::UserManagementInterface::Callback_RPCObject_existsUserPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_existsUser(username, &__ctx, __del, __cookie);
    }

    bool end_existsUser(const ::Ice::AsyncResultPtr&);
    
private:

    bool existsUser(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_existsUser(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int userCount()
    {
        return userCount(0);
    }
    ::Ice::Int userCount(const ::Ice::Context& __ctx)
    {
        return userCount(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_userCount(const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_userCount(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_userCount(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_userCount(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_userCount(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_userCount(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_userCount(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_userCount(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_userCount(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (::Ice::Int)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (::Ice::Int)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
                ::Ice::Int __ret;
                try
                {
                    __ret = __proxy->end_userCount(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (::Ice::Int)> _response;
        };
        return begin_userCount(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_userCount()
    {
        return begin_userCount(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_userCount(const ::Ice::Context& __ctx)
    {
        return begin_userCount(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_userCount(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_userCount(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_userCount(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_userCount(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_userCount(const ::UserManagementInterface::Callback_RPCObject_userCountPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_userCount(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_userCount(const ::Ice::Context& __ctx, const ::UserManagementInterface::Callback_RPCObject_userCountPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_userCount(&__ctx, __del, __cookie);
    }

    ::Ice::Int end_userCount(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int userCount(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_userCount(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<RPCObject> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_secure(bool __secure) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_twoway() const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_oneway() const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_batchOneway() const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_datagram() const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_batchDatagram() const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_compress(bool __compress) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_timeout(int __timeout) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<RPCObject> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<RPCObject*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace UserManagementInterface
{

class RPCObject : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual ::UserManagementInterface::statuscode addUser(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, ::Ice::Long, bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::UserManagementInterface::statuscode changeUserPassword(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::UserManagementInterface::statuscode changeUserQuota(const ::std::string&, ::Ice::Long, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool existsUser(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::Ice::Int userCount(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace UserManagementInterface
{

class RPCObject : virtual public ::IceDelegate::UserManagementInterface::RPCObject,
                  virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual ::UserManagementInterface::statuscode addUser(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, ::Ice::Long, bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::UserManagementInterface::statuscode changeUserPassword(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::UserManagementInterface::statuscode changeUserQuota(const ::std::string&, ::Ice::Long, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool existsUser(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int userCount(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace UserManagementInterface
{

class RPCObject : virtual public ::IceDelegate::UserManagementInterface::RPCObject,
                  virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual ::UserManagementInterface::statuscode addUser(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, ::Ice::Long, bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::UserManagementInterface::statuscode changeUserPassword(const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::UserManagementInterface::statuscode changeUserQuota(const ::std::string&, ::Ice::Long, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool existsUser(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::Ice::Int userCount(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace UserManagementInterface
{

class RPCObject : virtual public ::Ice::Object
{
public:

    typedef RPCObjectPrx ProxyType;
    typedef RPCObjectPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::UserManagementInterface::statuscode addUser(const ::std::string&, const ::std::string&, const ::std::string&, const ::std::string&, ::Ice::Long, bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___addUser(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::UserManagementInterface::statuscode changeUserPassword(const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___changeUserPassword(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::UserManagementInterface::statuscode changeUserQuota(const ::std::string&, ::Ice::Long, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___changeUserQuota(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool existsUser(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___existsUser(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int userCount(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___userCount(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const RPCObject& l, const RPCObject& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const RPCObject& l, const RPCObject& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace UserManagementInterface
{

template<class T>
class CallbackNC_RPCObject_addUser : public Callback_RPCObject_addUser_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::UserManagementInterface::statuscode);

    CallbackNC_RPCObject_addUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::UserManagementInterface::statuscode __ret;
        try
        {
            __ret = __proxy->end_addUser(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_RPCObject_addUserPtr
newCallback_RPCObject_addUser(const IceUtil::Handle<T>& instance, void (T::*cb)(::UserManagementInterface::statuscode), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_addUser<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RPCObject_addUserPtr
newCallback_RPCObject_addUser(T* instance, void (T::*cb)(::UserManagementInterface::statuscode), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_addUser<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_RPCObject_addUser : public Callback_RPCObject_addUser_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::UserManagementInterface::statuscode, const CT&);

    Callback_RPCObject_addUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::UserManagementInterface::statuscode __ret;
        try
        {
            __ret = __proxy->end_addUser(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_RPCObject_addUserPtr
newCallback_RPCObject_addUser(const IceUtil::Handle<T>& instance, void (T::*cb)(::UserManagementInterface::statuscode, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_addUser<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RPCObject_addUserPtr
newCallback_RPCObject_addUser(T* instance, void (T::*cb)(::UserManagementInterface::statuscode, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_addUser<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_RPCObject_changeUserPassword : public Callback_RPCObject_changeUserPassword_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::UserManagementInterface::statuscode);

    CallbackNC_RPCObject_changeUserPassword(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::UserManagementInterface::statuscode __ret;
        try
        {
            __ret = __proxy->end_changeUserPassword(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_RPCObject_changeUserPasswordPtr
newCallback_RPCObject_changeUserPassword(const IceUtil::Handle<T>& instance, void (T::*cb)(::UserManagementInterface::statuscode), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_changeUserPassword<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RPCObject_changeUserPasswordPtr
newCallback_RPCObject_changeUserPassword(T* instance, void (T::*cb)(::UserManagementInterface::statuscode), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_changeUserPassword<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_RPCObject_changeUserPassword : public Callback_RPCObject_changeUserPassword_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::UserManagementInterface::statuscode, const CT&);

    Callback_RPCObject_changeUserPassword(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::UserManagementInterface::statuscode __ret;
        try
        {
            __ret = __proxy->end_changeUserPassword(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_RPCObject_changeUserPasswordPtr
newCallback_RPCObject_changeUserPassword(const IceUtil::Handle<T>& instance, void (T::*cb)(::UserManagementInterface::statuscode, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_changeUserPassword<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RPCObject_changeUserPasswordPtr
newCallback_RPCObject_changeUserPassword(T* instance, void (T::*cb)(::UserManagementInterface::statuscode, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_changeUserPassword<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_RPCObject_changeUserQuota : public Callback_RPCObject_changeUserQuota_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::UserManagementInterface::statuscode);

    CallbackNC_RPCObject_changeUserQuota(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::UserManagementInterface::statuscode __ret;
        try
        {
            __ret = __proxy->end_changeUserQuota(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_RPCObject_changeUserQuotaPtr
newCallback_RPCObject_changeUserQuota(const IceUtil::Handle<T>& instance, void (T::*cb)(::UserManagementInterface::statuscode), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_changeUserQuota<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RPCObject_changeUserQuotaPtr
newCallback_RPCObject_changeUserQuota(T* instance, void (T::*cb)(::UserManagementInterface::statuscode), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_changeUserQuota<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_RPCObject_changeUserQuota : public Callback_RPCObject_changeUserQuota_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::UserManagementInterface::statuscode, const CT&);

    Callback_RPCObject_changeUserQuota(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::UserManagementInterface::statuscode __ret;
        try
        {
            __ret = __proxy->end_changeUserQuota(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_RPCObject_changeUserQuotaPtr
newCallback_RPCObject_changeUserQuota(const IceUtil::Handle<T>& instance, void (T::*cb)(::UserManagementInterface::statuscode, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_changeUserQuota<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RPCObject_changeUserQuotaPtr
newCallback_RPCObject_changeUserQuota(T* instance, void (T::*cb)(::UserManagementInterface::statuscode, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_changeUserQuota<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_RPCObject_existsUser : public Callback_RPCObject_existsUser_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_RPCObject_existsUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_existsUser(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_RPCObject_existsUserPtr
newCallback_RPCObject_existsUser(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_existsUser<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RPCObject_existsUserPtr
newCallback_RPCObject_existsUser(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_existsUser<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_RPCObject_existsUser : public Callback_RPCObject_existsUser_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_RPCObject_existsUser(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_existsUser(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_RPCObject_existsUserPtr
newCallback_RPCObject_existsUser(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_existsUser<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RPCObject_existsUserPtr
newCallback_RPCObject_existsUser(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_existsUser<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_RPCObject_userCount : public Callback_RPCObject_userCount_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_RPCObject_userCount(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_userCount(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_RPCObject_userCountPtr
newCallback_RPCObject_userCount(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_userCount<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_RPCObject_userCountPtr
newCallback_RPCObject_userCount(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_RPCObject_userCount<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_RPCObject_userCount : public Callback_RPCObject_userCount_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_RPCObject_userCount(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::UserManagementInterface::RPCObjectPrx __proxy = ::UserManagementInterface::RPCObjectPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_userCount(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_RPCObject_userCountPtr
newCallback_RPCObject_userCount(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_userCount<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_RPCObject_userCountPtr
newCallback_RPCObject_userCount(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_RPCObject_userCount<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
