// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `UserManagementInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <UserManagementInterface.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __UserManagementInterface__RPCObject__addUser_name = "addUser";

const ::std::string __UserManagementInterface__RPCObject__changeUserPassword_name = "changeUserPassword";

const ::std::string __UserManagementInterface__RPCObject__changeUserQuota_name = "changeUserQuota";

const ::std::string __UserManagementInterface__RPCObject__existsUser_name = "existsUser";

const ::std::string __UserManagementInterface__RPCObject__userCount_name = "userCount";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::UserManagementInterface::upCast(::IceProxy::UserManagementInterface::RPCObject* p) { return p; }

void
::IceProxy::UserManagementInterface::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::UserManagementInterface::RPCObject>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::UserManagementInterface::RPCObject;
        v->__copyFrom(proxy);
    }
}

::UserManagementInterface::statuscode
IceProxy::UserManagementInterface::RPCObject::addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UserManagementInterface__RPCObject__addUser_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UserManagementInterface__RPCObject__addUser_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UserManagementInterface::RPCObject* __del = dynamic_cast< ::IceDelegate::UserManagementInterface::RPCObject*>(__delBase.get());
            return __del->addUser(username, name, password, domain, quota, active, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UserManagementInterface::RPCObject::begin_addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UserManagementInterface__RPCObject__addUser_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UserManagementInterface__RPCObject__addUser_name, __del, __cookie);
    try
    {
        __result->__prepare(__UserManagementInterface__RPCObject__addUser_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(username);
        __os->write(name);
        __os->write(password);
        __os->write(domain);
        __os->write(quota);
        __os->write(active);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::UserManagementInterface::statuscode
IceProxy::UserManagementInterface::RPCObject::end_addUser(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UserManagementInterface__RPCObject__addUser_name);
    ::UserManagementInterface::statuscode __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::UserManagementInterface::statuscode
IceProxy::UserManagementInterface::RPCObject::changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UserManagementInterface__RPCObject__changeUserPassword_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UserManagementInterface__RPCObject__changeUserPassword_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UserManagementInterface::RPCObject* __del = dynamic_cast< ::IceDelegate::UserManagementInterface::RPCObject*>(__delBase.get());
            return __del->changeUserPassword(usernam, newpassword, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UserManagementInterface::RPCObject::begin_changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UserManagementInterface__RPCObject__changeUserPassword_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UserManagementInterface__RPCObject__changeUserPassword_name, __del, __cookie);
    try
    {
        __result->__prepare(__UserManagementInterface__RPCObject__changeUserPassword_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(usernam);
        __os->write(newpassword);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::UserManagementInterface::statuscode
IceProxy::UserManagementInterface::RPCObject::end_changeUserPassword(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UserManagementInterface__RPCObject__changeUserPassword_name);
    ::UserManagementInterface::statuscode __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::UserManagementInterface::statuscode
IceProxy::UserManagementInterface::RPCObject::changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UserManagementInterface__RPCObject__changeUserQuota_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UserManagementInterface__RPCObject__changeUserQuota_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UserManagementInterface::RPCObject* __del = dynamic_cast< ::IceDelegate::UserManagementInterface::RPCObject*>(__delBase.get());
            return __del->changeUserQuota(username, quota, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UserManagementInterface::RPCObject::begin_changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UserManagementInterface__RPCObject__changeUserQuota_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UserManagementInterface__RPCObject__changeUserQuota_name, __del, __cookie);
    try
    {
        __result->__prepare(__UserManagementInterface__RPCObject__changeUserQuota_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(username);
        __os->write(quota);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::UserManagementInterface::statuscode
IceProxy::UserManagementInterface::RPCObject::end_changeUserQuota(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UserManagementInterface__RPCObject__changeUserQuota_name);
    ::UserManagementInterface::statuscode __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::UserManagementInterface::RPCObject::existsUser(const ::std::string& username, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UserManagementInterface__RPCObject__existsUser_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UserManagementInterface__RPCObject__existsUser_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UserManagementInterface::RPCObject* __del = dynamic_cast< ::IceDelegate::UserManagementInterface::RPCObject*>(__delBase.get());
            return __del->existsUser(username, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UserManagementInterface::RPCObject::begin_existsUser(const ::std::string& username, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UserManagementInterface__RPCObject__existsUser_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UserManagementInterface__RPCObject__existsUser_name, __del, __cookie);
    try
    {
        __result->__prepare(__UserManagementInterface__RPCObject__existsUser_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(username);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::UserManagementInterface::RPCObject::end_existsUser(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UserManagementInterface__RPCObject__existsUser_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::Ice::Int
IceProxy::UserManagementInterface::RPCObject::userCount(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __UserManagementInterface__RPCObject__userCount_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__UserManagementInterface__RPCObject__userCount_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::UserManagementInterface::RPCObject* __del = dynamic_cast< ::IceDelegate::UserManagementInterface::RPCObject*>(__delBase.get());
            return __del->userCount(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::UserManagementInterface::RPCObject::begin_userCount(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__UserManagementInterface__RPCObject__userCount_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __UserManagementInterface__RPCObject__userCount_name, __del, __cookie);
    try
    {
        __result->__prepare(__UserManagementInterface__RPCObject__userCount_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::UserManagementInterface::RPCObject::end_userCount(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __UserManagementInterface__RPCObject__userCount_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::UserManagementInterface::RPCObject::ice_staticId()
{
    return ::UserManagementInterface::RPCObject::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::UserManagementInterface::RPCObject::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::UserManagementInterface::RPCObject);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::UserManagementInterface::RPCObject::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::UserManagementInterface::RPCObject);
}

::IceProxy::Ice::Object*
IceProxy::UserManagementInterface::RPCObject::__newInstance() const
{
    return new RPCObject;
}

::UserManagementInterface::statuscode
IceDelegateM::UserManagementInterface::RPCObject::addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UserManagementInterface__RPCObject__addUser_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(username);
        __os->write(name);
        __os->write(password);
        __os->write(domain);
        __os->write(quota);
        __os->write(active);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::UserManagementInterface::statuscode __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::UserManagementInterface::statuscode
IceDelegateM::UserManagementInterface::RPCObject::changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UserManagementInterface__RPCObject__changeUserPassword_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(usernam);
        __os->write(newpassword);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::UserManagementInterface::statuscode __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::UserManagementInterface::statuscode
IceDelegateM::UserManagementInterface::RPCObject::changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UserManagementInterface__RPCObject__changeUserQuota_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(username);
        __os->write(quota);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::UserManagementInterface::statuscode __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::UserManagementInterface::RPCObject::existsUser(const ::std::string& username, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UserManagementInterface__RPCObject__existsUser_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(username);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::Ice::Int
IceDelegateM::UserManagementInterface::RPCObject::userCount(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __UserManagementInterface__RPCObject__userCount_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::UserManagementInterface::statuscode
IceDelegateD::UserManagementInterface::RPCObject::addUser(const ::std::string& username, const ::std::string& name, const ::std::string& password, const ::std::string& domain, ::Ice::Long quota, bool active, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::UserManagementInterface::statuscode& __result, const ::std::string& __p_username, const ::std::string& __p_name, const ::std::string& __p_password, const ::std::string& __p_domain, ::Ice::Long __p_quota, bool __p_active, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_username(__p_username),
            _m_name(__p_name),
            _m_password(__p_password),
            _m_domain(__p_domain),
            _m_quota(__p_quota),
            _m_active(__p_active)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UserManagementInterface::RPCObject* servant = dynamic_cast< ::UserManagementInterface::RPCObject*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->addUser(_m_username, _m_name, _m_password, _m_domain, _m_quota, _m_active, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::UserManagementInterface::statuscode& _result;
        const ::std::string& _m_username;
        const ::std::string& _m_name;
        const ::std::string& _m_password;
        const ::std::string& _m_domain;
        ::Ice::Long _m_quota;
        bool _m_active;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UserManagementInterface__RPCObject__addUser_name, ::Ice::Normal, __context);
    ::UserManagementInterface::statuscode __result;
    try
    {
        _DirectI __direct(__result, username, name, password, domain, quota, active, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::UserManagementInterface::statuscode
IceDelegateD::UserManagementInterface::RPCObject::changeUserPassword(const ::std::string& usernam, const ::std::string& newpassword, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::UserManagementInterface::statuscode& __result, const ::std::string& __p_usernam, const ::std::string& __p_newpassword, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_usernam(__p_usernam),
            _m_newpassword(__p_newpassword)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UserManagementInterface::RPCObject* servant = dynamic_cast< ::UserManagementInterface::RPCObject*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->changeUserPassword(_m_usernam, _m_newpassword, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::UserManagementInterface::statuscode& _result;
        const ::std::string& _m_usernam;
        const ::std::string& _m_newpassword;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UserManagementInterface__RPCObject__changeUserPassword_name, ::Ice::Normal, __context);
    ::UserManagementInterface::statuscode __result;
    try
    {
        _DirectI __direct(__result, usernam, newpassword, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::UserManagementInterface::statuscode
IceDelegateD::UserManagementInterface::RPCObject::changeUserQuota(const ::std::string& username, ::Ice::Long quota, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::UserManagementInterface::statuscode& __result, const ::std::string& __p_username, ::Ice::Long __p_quota, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_username(__p_username),
            _m_quota(__p_quota)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UserManagementInterface::RPCObject* servant = dynamic_cast< ::UserManagementInterface::RPCObject*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->changeUserQuota(_m_username, _m_quota, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::UserManagementInterface::statuscode& _result;
        const ::std::string& _m_username;
        ::Ice::Long _m_quota;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UserManagementInterface__RPCObject__changeUserQuota_name, ::Ice::Normal, __context);
    ::UserManagementInterface::statuscode __result;
    try
    {
        _DirectI __direct(__result, username, quota, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::UserManagementInterface::RPCObject::existsUser(const ::std::string& username, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::std::string& __p_username, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_username(__p_username)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UserManagementInterface::RPCObject* servant = dynamic_cast< ::UserManagementInterface::RPCObject*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->existsUser(_m_username, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::std::string& _m_username;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UserManagementInterface__RPCObject__existsUser_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, username, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Int
IceDelegateD::UserManagementInterface::RPCObject::userCount(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::UserManagementInterface::RPCObject* servant = dynamic_cast< ::UserManagementInterface::RPCObject*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->userCount(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __UserManagementInterface__RPCObject__userCount_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* UserManagementInterface::upCast(::UserManagementInterface::RPCObject* p) { return p; }

namespace
{
const ::std::string __UserManagementInterface__RPCObject_ids[2] =
{
    "::Ice::Object",
    "::UserManagementInterface::RPCObject"
};

}

bool
UserManagementInterface::RPCObject::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__UserManagementInterface__RPCObject_ids, __UserManagementInterface__RPCObject_ids + 2, _s);
}

::std::vector< ::std::string>
UserManagementInterface::RPCObject::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__UserManagementInterface__RPCObject_ids[0], &__UserManagementInterface__RPCObject_ids[2]);
}

const ::std::string&
UserManagementInterface::RPCObject::ice_id(const ::Ice::Current&) const
{
    return __UserManagementInterface__RPCObject_ids[1];
}

const ::std::string&
UserManagementInterface::RPCObject::ice_staticId()
{
    return __UserManagementInterface__RPCObject_ids[1];
}

::Ice::DispatchStatus
UserManagementInterface::RPCObject::___addUser(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string username;
    ::std::string name;
    ::std::string password;
    ::std::string domain;
    ::Ice::Long quota;
    bool active;
    __is->read(username);
    __is->read(name);
    __is->read(password);
    __is->read(domain);
    __is->read(quota);
    __is->read(active);
    __inS.endReadParams();
    ::UserManagementInterface::statuscode __ret = addUser(username, name, password, domain, quota, active, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
UserManagementInterface::RPCObject::___changeUserPassword(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string usernam;
    ::std::string newpassword;
    __is->read(usernam);
    __is->read(newpassword);
    __inS.endReadParams();
    ::UserManagementInterface::statuscode __ret = changeUserPassword(usernam, newpassword, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
UserManagementInterface::RPCObject::___changeUserQuota(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string username;
    ::Ice::Long quota;
    __is->read(username);
    __is->read(quota);
    __inS.endReadParams();
    ::UserManagementInterface::statuscode __ret = changeUserQuota(username, quota, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
UserManagementInterface::RPCObject::___existsUser(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string username;
    __is->read(username);
    __inS.endReadParams();
    bool __ret = existsUser(username, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
UserManagementInterface::RPCObject::___userCount(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Int __ret = userCount(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __UserManagementInterface__RPCObject_all[] =
{
    "addUser",
    "changeUserPassword",
    "changeUserQuota",
    "existsUser",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "userCount"
};

}

::Ice::DispatchStatus
UserManagementInterface::RPCObject::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__UserManagementInterface__RPCObject_all, __UserManagementInterface__RPCObject_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __UserManagementInterface__RPCObject_all)
    {
        case 0:
        {
            return ___addUser(in, current);
        }
        case 1:
        {
            return ___changeUserPassword(in, current);
        }
        case 2:
        {
            return ___changeUserQuota(in, current);
        }
        case 3:
        {
            return ___existsUser(in, current);
        }
        case 4:
        {
            return ___ice_id(in, current);
        }
        case 5:
        {
            return ___ice_ids(in, current);
        }
        case 6:
        {
            return ___ice_isA(in, current);
        }
        case 7:
        {
            return ___ice_ping(in, current);
        }
        case 8:
        {
            return ___userCount(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
UserManagementInterface::RPCObject::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
UserManagementInterface::RPCObject::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
UserManagementInterface::__patch(RPCObjectPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::UserManagementInterface::RPCObjectPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::UserManagementInterface::RPCObject::ice_staticId(), v);
    }
}
